// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/lychee/openapi/tts/tts_stream.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TtsStreamService_StreamTts_FullMethodName = "/lychee.openapi.tts.TtsStreamService/StreamTts"
)

// TtsStreamServiceClient is the client API for TtsStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TtsStreamServiceClient interface {
	StreamTts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TtsStreamRequest, TtsStreamResponse], error)
}

type ttsStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTtsStreamServiceClient(cc grpc.ClientConnInterface) TtsStreamServiceClient {
	return &ttsStreamServiceClient{cc}
}

func (c *ttsStreamServiceClient) StreamTts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TtsStreamRequest, TtsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TtsStreamService_ServiceDesc.Streams[0], TtsStreamService_StreamTts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TtsStreamRequest, TtsStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TtsStreamService_StreamTtsClient = grpc.BidiStreamingClient[TtsStreamRequest, TtsStreamResponse]

// TtsStreamServiceServer is the server API for TtsStreamService service.
// All implementations must embed UnimplementedTtsStreamServiceServer
// for forward compatibility.
type TtsStreamServiceServer interface {
	StreamTts(grpc.BidiStreamingServer[TtsStreamRequest, TtsStreamResponse]) error
	mustEmbedUnimplementedTtsStreamServiceServer()
}

// UnimplementedTtsStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTtsStreamServiceServer struct{}

func (UnimplementedTtsStreamServiceServer) StreamTts(grpc.BidiStreamingServer[TtsStreamRequest, TtsStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTts not implemented")
}
func (UnimplementedTtsStreamServiceServer) mustEmbedUnimplementedTtsStreamServiceServer() {}
func (UnimplementedTtsStreamServiceServer) testEmbeddedByValue()                          {}

// UnsafeTtsStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TtsStreamServiceServer will
// result in compilation errors.
type UnsafeTtsStreamServiceServer interface {
	mustEmbedUnimplementedTtsStreamServiceServer()
}

func RegisterTtsStreamServiceServer(s grpc.ServiceRegistrar, srv TtsStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedTtsStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TtsStreamService_ServiceDesc, srv)
}

func _TtsStreamService_StreamTts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TtsStreamServiceServer).StreamTts(&grpc.GenericServerStream[TtsStreamRequest, TtsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TtsStreamService_StreamTtsServer = grpc.BidiStreamingServer[TtsStreamRequest, TtsStreamResponse]

// TtsStreamService_ServiceDesc is the grpc.ServiceDesc for TtsStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TtsStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lychee.openapi.tts.TtsStreamService",
	HandlerType: (*TtsStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTts",
			Handler:       _TtsStreamService_StreamTts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/lychee/openapi/tts/tts_stream.proto",
}
