// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/lychee/openapi/tts/tts_stream.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TtsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsStreamRequest) Reset() {
	*x = TtsStreamRequest{}
	mi := &file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsStreamRequest) ProtoMessage() {}

func (x *TtsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsStreamRequest.ProtoReflect.Descriptor instead.
func (*TtsStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_lychee_openapi_tts_tts_stream_proto_rawDescGZIP(), []int{0}
}

func (x *TtsStreamRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TtsStreamRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *TtsStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TtsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsStreamResponse) Reset() {
	*x = TtsStreamResponse{}
	mi := &file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsStreamResponse) ProtoMessage() {}

func (x *TtsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsStreamResponse.ProtoReflect.Descriptor instead.
func (*TtsStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_lychee_openapi_tts_tts_stream_proto_rawDescGZIP(), []int{1}
}

func (x *TtsStreamResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TtsStreamResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_lychee_openapi_tts_tts_stream_proto protoreflect.FileDescriptor

const file_proto_lychee_openapi_tts_tts_stream_proto_rawDesc = "" +
	"\n" +
	")proto/lychee/openapi/tts/tts_stream.proto\x12\x12lychee.openapi.tts\"d\n" +
	"\x10TtsStreamRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"L\n" +
	"\x11TtsStreamResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2p\n" +
	"\x10TtsStreamService\x12\\\n" +
	"\tStreamTts\x12$.lychee.openapi.tts.TtsStreamRequest\x1a%.lychee.openapi.tts.TtsStreamResponse(\x010\x01B=Z;github.com/lycheeAIc/voice-openapi-go-sdk/tts/grpcpb;grpcpbb\x06proto3"

var (
	file_proto_lychee_openapi_tts_tts_stream_proto_rawDescOnce sync.Once
	file_proto_lychee_openapi_tts_tts_stream_proto_rawDescData []byte
)

func file_proto_lychee_openapi_tts_tts_stream_proto_rawDescGZIP() []byte {
	file_proto_lychee_openapi_tts_tts_stream_proto_rawDescOnce.Do(func() {
		file_proto_lychee_openapi_tts_tts_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lychee_openapi_tts_tts_stream_proto_rawDesc), len(file_proto_lychee_openapi_tts_tts_stream_proto_rawDesc)))
	})
	return file_proto_lychee_openapi_tts_tts_stream_proto_rawDescData
}

var file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lychee_openapi_tts_tts_stream_proto_goTypes = []any{
	(*TtsStreamRequest)(nil),  // 0: lychee.openapi.tts.TtsStreamRequest
	(*TtsStreamResponse)(nil), // 1: lychee.openapi.tts.TtsStreamResponse
}
var file_proto_lychee_openapi_tts_tts_stream_proto_depIdxs = []int32{
	0, // 0: lychee.openapi.tts.TtsStreamService.StreamTts:input_type -> lychee.openapi.tts.TtsStreamRequest
	1, // 1: lychee.openapi.tts.TtsStreamService.StreamTts:output_type -> lychee.openapi.tts.TtsStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lychee_openapi_tts_tts_stream_proto_init() }
func file_proto_lychee_openapi_tts_tts_stream_proto_init() {
	if File_proto_lychee_openapi_tts_tts_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lychee_openapi_tts_tts_stream_proto_rawDesc), len(file_proto_lychee_openapi_tts_tts_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lychee_openapi_tts_tts_stream_proto_goTypes,
		DependencyIndexes: file_proto_lychee_openapi_tts_tts_stream_proto_depIdxs,
		MessageInfos:      file_proto_lychee_openapi_tts_tts_stream_proto_msgTypes,
	}.Build()
	File_proto_lychee_openapi_tts_tts_stream_proto = out.File
	file_proto_lychee_openapi_tts_tts_stream_proto_goTypes = nil
	file_proto_lychee_openapi_tts_tts_stream_proto_depIdxs = nil
}
